### ISSUE TITLE
Белый цвет в консоли потускнел

### ISSUE THREAD

**Issue by hgruntt** [FWGS/mainui_cpp#106]
До обновления Xash до последней версии консоль выглядела так:
![Metro Redux Screenshot 2024 06 04 - 07 24 10 76](https://github.com/FWGS/mainui_cpp/assets/161692606/4be4bbad-90aa-405b-a491-11dfe7d12cc0)
После обновления:
![Metro Redux Screenshot 2024 06 04 - 07 24 57 95](https://github.com/FWGS/mainui_cpp/assets/161692606/88730359-2887-4a01-a555-8b04d33e620b)

**Comment by hgruntt** [comment]
Вместе c @Aynekko выяснили что значение читается не из квара а из colors.lst

**Comment by hgruntt** [comment]
ошибка, не туда сделан issue

**Comment by a1batross** [comment]
Ну так логично, потому что colors.lst оверрайдит и блокирует con_color на случай если там задано какой-то недефолтный цвет.

con_color в оригинальном ксаше был командой и не сохранялся. Я переделал его в квар как расширение, что оказалось очень неодуманным решением, так как теперь он стал конфликтовать с colors.lst.
