### ISSUE TITLE
Credits.txt modified UTF-8 crashes the game

### ISSUE THREAD

**Issue by DavidMacalister** [FWGS/mainui_cpp#108]
I have a customized credits.txt file in UTF-8, but when the credits arrive the game crashes

[credits.txt](https://github.com/user-attachments/files/16399132/credits.txt)

**Comment by a1batross** [comment]
Fixed in https://github.com/FWGS/mainui_cpp/commit/a33a3d422a9bcdfcdb50771df4c69c35ce28ed89
