### ISSUE TITLE
Cash 

### ISSUE THREAD

**Issue by Skye450** [FWGS/mainui_cpp#116]
![Screenshot_2024-12-04-14-42-46-010_su.xash.engine.test.jpg](https://github.com/user-attachments/assets/ad26e90d-1809-40b2-981b-6ac20cd0a58c)

**Comment by a1batross** [comment]
Wrong repository.

CS16Client bugs must be sent to https://github.com/Velaron/cs16-client

**Comment by Skye450** [comment]
![Screenshot_2024-12-04-14-50-28-588_su.xash.engine.test.jpg](https://github.com/user-attachments/assets/d796b0a4-b93e-4785-a43d-377e88199afa)

**Comment by a1batross** [comment]
Don't publish unrelated random screenshots please.
