### ISSUE TITLE
Unable to translate strings with \n character

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/mainui_cpp#41]
Here's an example
![Снимок экрана (7)](https://user-images.githubusercontent.com/22411953/105710259-09fcaf80-5f41-11eb-84bf-91b15d3eceb0.png)

![Безымянный](https://user-images.githubusercontent.com/22411953/105711350-a4a9be00-5f42-11eb-9886-13fb6600f64e.png)

**Comment by lewa-j** [comment]
![img](https://user-images.githubusercontent.com/5416122/224358190-25adfc71-b3a5-4693-9dd2-05a83c2925e0.png)
just put a new line in place of \n

**Comment by a1batross** [comment]
This should be fixed in parser code.

**Comment by Vladislav4KZ** [comment]
Строки с ``\n`` переводились и раньше, но не переводилась только конкретная строка из скриншота. В последних билдах движка окно с этой строкой было вырезано из меню, т.к. предикт включается по умолчанию и больше не имеет своего пункта меню.

**Comment by Vladislav4KZ** [comment]
Способ от lewa_j для перевода уже другой строки с переносом у меня не работал как на новом, так и на старом движке.
На последнем билде нового движка этот способ тем более не требуется, т.к. строка теперь переводится без разделения.
