### ISSUE TITLE
Небольшие несовместимости с новым Ксашем.

### ISSUE THREAD

**Issue by ghost** [FWGS/mainui_cpp#44]
Заметил, что в mainui есть некоторые настройки, которые пытаются обращаться к кварам из старого движка, которых уже нету в новом:
menus/Audio.cpp - reverseChannels.
menus/GameOptions.cpp - split, compress, maxpacket и maxpayload.

**Comment by mittorn** [comment]
Второе в принципе в новом пока есть в режиме совместимости. Но надо понимать что в новом движке userinfo отделены от кваров и скорее всего это там не учтено

**Comment by mittorn** [comment]
В любом случае мультиплеер пока непригоден. Надо искать регрессии в оригинальном движке и править их

**Comment by Vladislav4KZ** [comment]
Неактуально.

Опция "Reverse audio channels" была удалена в этом коммите: https://github.com/FWGS/mainui_cpp/commit/d83d6c7e1c4012402e30a0cc96205d1572b74f7b

Split, compress, maxpacket и maxpayload были удалены из меню в этом коммите: https://github.com/FWGS/mainui_cpp/commit/16379c10c7ebafcbfaf355069ec5a405c77c8e24
