### ISSUE TITLE
Menu flickering when a mod is loaded

### ISSUE THREAD

**Issue by RobyKalilla** [FWGS/mainui_cpp#45]
I loaded Poke646 and it loaded it......but when the introduction starts......the game flickers and crashes, same thing happened with normal Half life too.

**Comment by a1batross** [comment]
Platform? GPU? Engine version? Half-Life was from Steam? Anything?

**Comment by RobyKalilla** [comment]
Windows 10 64bit version, I downloaded the latest release and Half life was the 2001 disc game of the year version.

**Comment by a1batross** [comment]
Engine version is printed at the right bottom edge in main menu.

**Comment by RobyKalilla** [comment]
v49/0.20

**Comment by RobyKalilla** [comment]
do you need the build number too?

**Comment by nekonomicon** [comment]
@RobyKalilla try the latest build from FWGS/xash3d-deploy repository.
0.20 release is not stable.

**Comment by RobyKalilla** [comment]
okay, thanks

**Comment by RobyKalilla** [comment]
the problem is.....I don't know to compile it, also what branch? can you send me a direct link? thanks

**Comment by Velaron** [comment]
You don't need to compile anything, just download a file from https://github.com/FWGS/xash3d-deploy/tree/anewengine-master

**Comment by RobyKalilla** [comment]
now it doesn't have that bug but I found other 2

**Comment by RobyKalilla** [comment]
all breakables sound and look always like glass

**Comment by RobyKalilla** [comment]
unless it's a crate

**Comment by RobyKalilla** [comment]
also the game crashes when it quits

**Comment by Velaron** [comment]
post every bug as a separate issue

**Comment by RobyKalilla** [comment]
oki
