### ISSUE TITLE
Краш при отмене включения игнорирования мыши

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/mainui_cpp#46]
Захожу в настройки управления -> Input devices нажимаю Ignore mouse потом Cancel и происходит краш движка
[engine.log](https://github.com/FWGS/mainui_cpp/files/6140534/engine.log)

**Comment by a1batross** [comment]
Должно быть пофикшено.

**Comment by Vladislav4KZ** [comment]
Да, действительно пофикшено.
