### ISSUE TITLE
В модах где заголовки сохранены в формате bmp, не читаются

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/mainui_cpp#49]
В модах где заголовки сохранены в формате bmp, не читаются (head_multiplayer.bmp и т. п.)
Вместо них используются картинки из extras.pak для Half-Life которые в формате .tga.

Если их удалить, то читаются картинки которые шли с модом в формате .bmp

**Comment by nekonomicon** [comment]
Приоритет загрузки в .tga специально для extras.pak делал @mittorn.
По какой причине даже не помню, но вероятно моды не проверялись.

**Comment by nekonomicon** [comment]
Нет, в старом движке по ходу фиксили приоритет загрузки.
В общем, вот:
https://github.com/FWGS/xash3d-fwgs/pull/899
