### ISSUE TITLE
Не отображается логотип игры (logo.avi)

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/mainui_cpp#52]
Не отображается логотип игры (logo.avi) когда используется фон из WON версии Half-Life
Сам файл logo.avi присутствует

**Comment by hiIexistlol** [comment]
there's also the intro menus, but they mentioned this already in [#16](https://github.com/FWGS/xash3d-fwgs/issues/16)

**Comment by a1batross** [comment]
Duplicate of #16
