### ISSUE TITLE
Обнаружение файлов со звуками нажатия кнопок в меню.

### ISSUE THREAD

**Issue by nekonomicon** [FWGS/mainui_cpp#55]
Файлы из списка ниже в WON HL лежали в папке `media`, а в Steam HL их переместили в `sound/common`:
```
launch_deny1.wav
launch_deny2.wav
launch_dnmenu1.wav
launch_glow1.wav 
launch_select1.wav
launch_select2.wav
launch_upmenu1.wav
```
Возможно, будет лучше реализовать обнаружение этих файлов в указанных директориях и убрать их из [FWGS/xash-extras](https://github.com/FWGS/xash-extras/tree/master/media).

Спасибо @Velaron за наводку.

**Comment by Vladislav4KZ** [comment]
Но в модах эти звуки лежат всегда в папке media.
Также в WON версии эти звуки лежали как и в папке media так и в sound/common

**Comment by nekonomicon** [comment]
Тем более, из экстрасов эти файлы нужно убрать.

**Comment by Vladislav4KZ** [comment]
Думаю, можно закрывать так как это уже сделано https://github.com/FWGS/mainui_cpp/commit/132b9f755f303c4133fe8eefb2625a11cbca7c1b

Всё нормально работает, кастомные звуки меню из модов проигрываются и звуки меню из sound/common тоже проигрываются, когда их нет в папке media

**Comment by nekonomicon** [comment]
Исправлено https://github.com/FWGS/mainui_cpp/commit/132b9f755f303c4133fe8eefb2625a11cbca7c1b
