### ISSUE TITLE
Можно сохранить только одно пользовательское сохранение через меню

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/mainui_cpp#59]
Когда ты сохранил игру выбрав пункт New saved game игра сохраняется, и если опять создать "Новое" сохранение, то оно перезапишет старое Новое.sav

В Half-Life на GoldSource можно создавать новые сохранения хоть до бесконечности, в названиях файлов сохранений пишется Half-Life с трёхзначным числом, типа Half-Life-000.sav Half-Life-001.sav и т.д.

**Comment by Vladislav4KZ** [comment]
Этот баг по какой-то причине случается только на русской локализации игры, на английской все нормально.

**Comment by Vladislav4KZ** [comment]
Включите русский язык кваром `ui_language russian` чтобы воспроизвести баг. Это как-то связано с локализацией строки из gameui_russian.txt `#GameUI_SaveGame_New`

**Comment by a1batross** [comment]
Fixed in 97fcbf8
