### ISSUE TITLE
Transitional Menu Builder?

### ISSUE THREAD

**Issue by a1batross** [FWGS/mainui_cpp#7]
Should this ever be implemented? 
I see this something like:
```
CMenuTransitional::Builder builder;
builder.SetBanner(ART_BANNER_CONFIGURATION)
 .AddButton(PC_AUDIO, "Audio', "Configure Audio", UI_Audio_Menu)
 .AddButton(PC_SOMETHINGELSE,...)
 .AddButton(PC_UPDATE, "Update", "Update engine", UI_ShowUpdateDialog);
 .AddReturnButton();
CMenuTransitional *configuration = builder.Build();
configuration.Open();
delete configuration;
```

**Comment by a1batross** [comment]
Funny thing. Some easy menus, like CMenuTouch or CMenuVideo can be removed and replacing by instancing CMenuFramework and placing buttons.

**Comment by mittorn** [comment]
What we will do with delete on opened menu?

**Comment by a1batross** [comment]
What do you mean "delete"?  As I remember, there is nothing bound to "delete" key. And we don't need to "delete" object if it's static. :)

**Comment by mittorn** [comment]
I think. builder should generate dynamic menus so we can delete builder and create new one

**Comment by a1batross** [comment]
Builder by design is an object which knows how to create and set up complex object. If builder doesn't need anymore, it can be deleted. If it can be reused, it MUST be reused. 

The object which it's builds also can be removed anytime. For example, build an object during Init function(Precache in mainui_cpp case) and delete it in Shutdown.

**Comment by a1batross** [comment]
Dynamic menu creation isn't a serious problem.
So I am closing this issue. If someone have a questions about dynamic menus, they should create new issue.
