### ISSUE TITLE
Срабатывание "assertion failed" при попытке подключиться к несуществующему серверу через сервер-браузер.

### ISSUE THREAD

**Issue by ghost** [FWGS/mainui_cpp#81]
Было замечено, что иногда сервер-браузер может делать кнопку "Join Game" активной, хотя не выделен ни один сервер, что приводит к срабатыванию "assertion failed".
В данный момент этот баг производится так:
1)Проскроллить список серверов до самого низа.
2)Переключиться на вкладку NAT.
3)Нажать кнопку  "Join Game".
![image](https://user-images.githubusercontent.com/96422615/184545744-4382dd6d-50c9-4abb-a4ea-20b34858555d.png)

**Comment by Vladislav4KZ** [comment]
> В данный момент этот баг производится так:
1)Проскроллить список серверов до самого низа.
2)Переключиться на вкладку NAT.
3)Нажать кнопку "Join Game".

У меня этот баг не воспроизводится.

Такое окно с ошибкой вылезало при удерживании полосы прокрутки до тех пор, пока список серверов не обновится. Но это уже было исправлено.

Проверял на:
Xash3D FWGS v49/0.20
Номер сборки: 3404
Тип сборки: win32-i386
Коммит: https://github.com/FWGS/xash3d-fwgs/commit/e70f9a67b85ef3184f058cd10480d32ef68d14eb
Ветка: master

ОС: Windows 10 Pro x64 22H2
Номер сборки ОС: 19045.4651

**Comment by Vladislav4KZ** [comment]
При нажатии кнопки "Join game" движок пытается присоединиться к серверу из вкладки NAT, когда она активна, но при этом сервер ещё не отображается в списке.

И по умолчанию всегда выделен первый сервер в списке, что во вкладке  Direct, что в NAT.
