### ISSUE TITLE
German translation of mainui_skeleton_everthing.txt

### ISSUE THREAD

**Issue by StenApp** [FWGS/mainui_cpp#98]
Hi,

i like to have one global translation file, no .lst files.
I translated all lines except for:

> "StringsList_188"                                                                                                                   ""
"StringsList_189"                                                                                                                   ""
"StringsList_190"                                                                                                                   ""
"StringsList_191"                                                                                                                   ""
"StringsList_192"                                                                                                                   ""
"StringsList_193"                                                                                                                   ""
"StringsList_198"                                                                                                                   ""
"StringsList_200"                                                                                                                   ""
"StringsList_201"                                                                                                                   ""
"StringsList_202"                                                                                                                   ""
"StringsList_234"                                                                                                                   ""
"StringsList_235"                                                                                                                   ""
"StringsList_240"                                                                                                                   ""
"StringsList_400"                                                                                                                   ""
"StringsList_530" ""

> 

 Where can i get the content of those strings?
Is this related to Opposing force? If so the german strings.lst contains slightly different numbers.
[strings.lst.txt](https://github.com/FWGS/mainui_cpp/files/12793167/strings.lst.txt)

**Comment by a1batross** [comment]
This, again, something I did for compatibility with WON based mods. In particular, `StringsList` tokens are the special cases for `strings.lst` file.

If you have `strings.lst` file, then you may remove these from the translation file. If not, you may use them to refer to `strings.lst` strings. The number is the index of the string in resource table of legacy `hl.exe` file, you may actually look up the meaning for some of them in `mainui_cpp` source: https://github.com/FWGS/mainui_cpp/blob/master/MenuStrings.cpp#L35

Remember, the `StringsList` token will take precedence over `strings.lst` file.

**Comment by a1batross** [comment]
In the state of half-translated game, which we discussed earlier, you don't actually need `mainui_skeleton_everything.txt` file. 

You can use `mainui_skeleton_stripped.txt` instead. (I just regenerated new, check the repository)

**Comment by StenApp** [comment]
Thank you for your explanation.
I translated all strings to german and i test mainui_skeleton_stripped.txt renamed to mainui_german.txt in valve\resource folder with ui_language german

**Comment by StenApp** [comment]
In the end i decided this: use completely translated mainui_skeleton_everything.txt renamed to mainui_german.txt and put in valve/resources with ui_language set to german.
My intention is to override all local files (valve_ and gameui_ and strings.lst files).
Thank you for your help!


Just for documentation:
Taken from resource.h (number to IDS string) and hl_res.rc (IDS string to translated text):

> #define IDS_MAIN_RETURNHELP             188
> #define IDS_MAIN_NEWGAMEHELP            189
> #define IDS_MAIN_TRAININGHELP           190
> #define IDS_MAIN_LOADHELP               191
> #define IDS_MAIN_LOADSAVEHELP           192
> #define IDS_MAIN_CONFIGUREHELP          193
> #define IDS_MAIN_MULTIPLAYERHELP        198
> #define IDS_NEWGAME_EASYHELP            200
> #define IDS_NEWGAME_MEDIUMHELP          201
> #define IDS_NEWGAME_DIFFICULTHELP       202
> #define IDS_TRAINING_EXITCURRENT        234
> #define IDS_MAIN_QUITPROMPTINGAME       235
> #define IDS_NEWGAME_NEWPROMPT           240
> #define IDS_MAIN_PREVIEWSHELP           400
> #define IDS_MAIN_CUSTOMHELP             530
