### ISSUE TITLE
Translation of chapter titles

### ISSUE THREAD

**Issue by StenApp** [FWGS/mainui_cpp#99]
I like to translate the level titles in the load/save menu.
I see them in my language in titles.txt but in the menu they stay cryptic:
![image](https://github.com/FWGS/mainui_cpp/assets/32524257/39fcd1c3-94a5-4846-9d02-ae204d76009b)

should be 

C0A0TITLE
{
ZIEL: BLACK MESA, ZENTRUM
}

**Comment by a1batross** [comment]
titles.txt aren't used there, it's in the `valve_english.txt` file.

As for mods, mods can't get save names translated until the mod specifically supports it through undocumented callback in the DLL. :(

**Comment by StenApp** [comment]
That's why...
I removed gamefoldername_language files.txt from resources subfolders.
only use mainui_german.txt set to ui_language german.
If i ad the chapter titles in mainui.txt it's getting translated.
Opposing force uses a gearbox_english.txt with only english chapter titles.
I have to translate this file then and save it as modfoldername_german.txt and put it in resource folder and set ui_language to german too.

**Comment by StenApp** [comment]
Ah now i see the confusion.
I talked about the chapter titels displayed in the menu not the savegame name.
I don't care about the savegame names.
